In [5]:
# F2, F3, F4의 Z-score 계산

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('Cross-Sectional Analysis - Sample data.csv')
df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2
...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2370 entries, 0 to 2369
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Symbol        2370 non-null   object
 1   Company_Name  2370 non-null   object
 2   Country       2370 non-null   object
 3   Sector        2370 non-null   object
 4   Industry      2370 non-null   object
 5   F1            2369 non-null   object
 6   F2            2366 non-null   float64
 7   F3            2366 non-null   float64
 8   F4            2083 non-null   object
dtypes: float64(2), object(7)
memory usage: 166.8+ KB

In [9]:
df['F4']

0         NaN
1       103.1
2        16.1
3         6.8
4         5.2
        ...
2365     47.8
2366     38.5
2367      NaN
2368      NaN
2369      9.8
Name: F4, Length: 2370, dtype: object

In [10]:
# F4를 object에서 float으로 전환

def process_number(data):
    return float(data.replace(',',''))

df['F4'] = df['F4'].astype('str')
df['F4'] = df['F4'].apply(process_number)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2370 entries, 0 to 2369
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Symbol        2370 non-null   object
 1   Company_Name  2370 non-null   object
 2   Country       2370 non-null   object
 3   Sector        2370 non-null   object
 4   Industry      2370 non-null   object
 5   F1            2369 non-null   object
 6   F2            2366 non-null   float64
 7   F3            2366 non-null   float64
 8   F4            2083 non-null   float64
dtypes: float64(3), object(6)
memory usage: 166.8+ KB

In [12]:
df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2
...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8

In [13]:
# F2, F3, F4 Z-score 계산

df[['F2_Z', 'F3_Z', 'F4_Z']] = (df[['F2', 'F3', 'F4']] - df[['F2', 'F3', 'F4']].mean()) / df[['F2', 'F3', 'F4']].std()
df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN,-0.798240,-0.936532,NaN
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1,0.685487,0.403961,1.544722
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1,0.388741,0.298133,-0.022873
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8,-0.649867,0.474513,-0.190443
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2,0.685487,0.298133,-0.219273
...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8,0.982232,1.956111,0.548308
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5,-0.798240,-0.160457,0.380738
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN,-0.946613,-0.936532,NaN
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN,-0.204749,-0.125181,NaN
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8,-0.056377,0.650894,-0.136388

In [14]:
# F2, F3, F4의 국가별 mean 계산

result = (
    df
    .groupby(['Country'])
    [['F2', 'F3', 'F4']].mean()
)

In [15]:
# 칼럼헤드 변경

result = result.rename({
    'F2':'F2_ctr_mean',
    'F3':'F3_ctr_mean',
    'F4':'F4_ctr_mean'
}, axis=1
)

In [16]:
result[:5]

           F2_ctr_mean  F3_ctr_mean  F4_ctr_mean
Country
@NA                NaN          NaN          NaN
Australia     0.529310     3.556897     8.775472
Austria       1.460000     2.660000    13.700000
Belgium       0.854545     2.500000     8.490000
Bermuda       1.650000     2.675000    29.533333

In [17]:
# 합병

merged_df = pd.merge(df, result, on = ['Country'], how = 'left')
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500

In [18]:
# F2, F3, F4의 국가별 표준편차 계산

result_std = (
    df
    .groupby(['Country'])
    [['F2', 'F3', 'F4']].std()
)

In [19]:
# 인덱스 이름 변경

result_std = result_std.rename({
    'F2':'F2_ctr_std',
    'F3':'F3_ctr_std',
    'F4':'F4_ctr_std'
}, axis=1)

In [20]:
result_std[:10]

           F2_ctr_std  F3_ctr_std  F4_ctr_std
Country
@NA               NaN         NaN         NaN
Australia    0.396037    2.606545   28.137614
Austria      1.234099    2.300652   10.137307
Belgium      0.478254    1.702351   16.931263
Bermuda      1.167619    1.998958   24.258263
Brazil       0.278204    3.497735   66.759300
Canada       0.324817    1.796559   44.432685
Chile        0.643852    8.078895   34.539711
China        1.142699    4.871468   59.198172
Colombia     0.309570    3.296842   19.573686

In [21]:
# 합병

merged_df = pd.merge(merged_df, result_std, on = ['Country'], how = 'left')
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578

In [22]:
# Q.이렇게 하는것보다 result로 하면 이점? 이걸 그대로 Z 계산할때 쓰면 단점?
# 이렇게 하면 데이터프레임이 저장되지 않음. result 방식으로 해야 저장 됨.

merged_df.groupby(['Country'])[['F2', 'F3', 'F4']].mean()[:5]

                 F2        F3         F4
Country
@NA             NaN       NaN        NaN
Australia  0.529310  3.556897   8.775472
Austria    1.460000  2.660000  13.700000
Belgium    0.854545  2.500000   8.490000
Bermuda    1.650000  2.675000  29.533333

In [23]:
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578

In [24]:
# 국가별 Z-score 계산 시, Columns must be same length as key 에러 (F2 하나씩 하면 정상작동)
# 에러메세지의 length는 # of columns가 아니라, 각 칼럼의 # of rows이다. 맞춰주고 난 뒤 시작해야 함.

merged_df['F2_ctr_Z'] = (merged_df['F2'] - merged_df['F2_ctr_mean']) / merged_df['F2_ctr_std']
merged_df['F3_ctr_Z'] = (merged_df['F3'] - merged_df['F3_ctr_mean']) / merged_df['F3_ctr_std']
merged_df['F4_ctr_Z'] = (merged_df['F4'] - merged_df['F4_ctr_mean']) / merged_df['F4_ctr_std']
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,...,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN,-0.798240,...,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1,0.685487,...,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1,0.388741,...,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8,-0.649867,...,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2,0.685487,...,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8,0.982232,...,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5,-0.798240,...,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN,-0.946613,...,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN,-0.204749,...,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8,-0.056377,...,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772

In [25]:
# Q.아래 방식으로는 왜 stat이 NA가 나오는지?
# F2_sct_mean, F2_sct_std 칼럼을 각각 따로 만들어서 해야하나봄.
# df[['F2_Z', 'F3_Z', 'F4_Z']] = (df[['F2', 'F3', 'F4']] - df[['F2', 'F3', 'F4']].mean()) / df[['F2', 'F3', 'F4']].std()
  # 이게 작동했던 이유는 groupby가 없어서인듯.

merged_df['F2_sct_mean'] = merged_df.groupby(['Sector'])['F2'].mean()
merged_df['F2_sct_Z'] = (merged_df['F2'] - merged_df.groupby(['Sector'])['F2'].mean()) / merged_df.groupby(['Sector'])['F2'].std()
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,...,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean,F2_sct_Z
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN,-0.798240,...,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1,0.685487,...,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1,0.388741,...,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8,-0.649867,...,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2,0.685487,...,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8,0.982232,...,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5,-0.798240,...,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN,-0.946613,...,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN,-0.204749,...,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8,-0.056377,...,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN

In [59]:
# F2_sct_mean & _std

result_mean = (
    merged_df
    .groupby(['Sector'])
    ['F2'].mean()
    .to_frame()
)

result_mean = result_mean.rename({'F2':'F2_sct_mean'}, axis=1)

result_std = (
    merged_df
    .groupby(['Sector'])
    ['F2'].std()
    .to_frame()
)

result_std = result_std.rename({'F2':'F2_sct_std'}, axis=1)

In [63]:
merged_df.drop(['F2_sct_mean_x'], axis=1)

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_Z,Z_sum,Z_sum_NA_sct_mean,Z_wt_sum,Z_wt_sum_NA_sct_mean,F1_pct_rank,Z_comb,F2_sct_mean_y
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,5365.9,0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,-0.353361,NaN,-0.230165,0.802448,NaN,0.359615
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,2147.2,1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,2.634169,2.634169,0.772876,0.772876,0.978472,2.634169,1.023333
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,14320.7,0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,0.664001,0.664001,0.279236,0.279236,0.447868,0.279236,1.023333
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,84749.9,0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,-0.365797,-0.365797,-0.220668,-0.220668,0.059941,-0.220668,0.575219
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,1746.6,1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,0.764347,0.764347,0.388329,0.388329,0.987759,0.764347,0.359615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,6911.6,1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,3.486651,3.486651,1.187611,1.187611,0.719713,3.486651,0.575219
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,6286.9,0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,-0.577960,-0.577960,-0.371110,-0.371110,0.751372,-0.577960,0.521154
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,18071.6,0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.369776,NaN,0.359851
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,15444.2,0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.422963,NaN,0.359851
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,67148.0,0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,0.458129,0.458129,0.139802,0.139802,0.084846,0.139802,1.023333

In [66]:
merged_df = pd.merge(merged_df, result_mean, on=['Sector'], how='left')
merged_df = pd.merge(merged_df, result_std, on=['Sector'], how='left')
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean_x,F2_sct_Z,Z_sum,Z_sum_NA_sct_mean,Z_wt_sum,Z_wt_sum_NA_sct_mean,F1_pct_rank,Z_comb,F2_sct_mean_y,F2_sct_mean_x,F2_sct_mean_y,F2_sct_mean,F2_sct_std
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,5365.9,0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,NaN,-0.353361,NaN,-0.230165,0.802448,NaN,0.359615,0.359615,0.359615,0.359615,0.358343
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,2147.2,1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN,2.634169,2.634169,0.772876,0.772876,0.978472,2.634169,1.023333,1.023333,1.023333,1.023333,0.786744
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,14320.7,0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN,0.664001,0.664001,0.279236,0.279236,0.447868,0.279236,1.023333,1.023333,1.023333,1.023333,0.786744
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,84749.9,0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN,-0.365797,-0.365797,-0.220668,-0.220668,0.059941,-0.220668,0.575219,0.575219,0.575219,0.575219,0.529314
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,1746.6,1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN,0.764347,0.764347,0.388329,0.388329,0.987759,0.764347,0.359615,0.359615,0.359615,0.359615,0.358343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,6911.6,1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN,3.486651,3.486651,1.187611,1.187611,0.719713,3.486651,0.575219,0.575219,0.575219,0.575219,0.529314
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,6286.9,0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN,-0.577960,-0.577960,-0.371110,-0.371110,0.751372,-0.577960,0.521154,0.521154,0.521154,0.521154,0.630418
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,18071.6,0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.369776,NaN,0.359851,0.359851,0.359851,0.359851,0.406323
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,15444.2,0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.422963,NaN,0.359851,0.359851,0.359851,0.359851,0.406323
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,67148.0,0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN,0.458129,0.458129,0.139802,0.139802,0.084846,0.139802,1.023333,1.023333,1.023333,1.023333,0.786744

In [68]:
merged_df['F2_sct_Z'] = (merged_df['F2'] - merged_df['F2_sct_mean']) / merged_df['F2_sct_std']
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean_x,F2_sct_Z,Z_sum,Z_sum_NA_sct_mean,Z_wt_sum,Z_wt_sum_NA_sct_mean,F1_pct_rank,Z_comb,F2_sct_mean_y,F2_sct_mean_x,F2_sct_mean_y,F2_sct_mean,F2_sct_std
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,5365.9,0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,-0.724489,NaN,-0.353361,NaN,-0.230165,0.802448,NaN,0.359615,0.359615,0.359615,0.359615,0.358343
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,2147.2,1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,0.097448,2.634169,2.634169,0.772876,0.772876,0.978472,2.634169,1.023333,1.023333,1.023333,1.023333,0.786744
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,14320.7,0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,-0.156764,0.664001,0.664001,0.279236,0.279236,0.447868,0.279236,1.023333,1.023333,1.023333,1.023333,0.786744
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,84749.9,0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,-0.708877,-0.365797,-0.365797,-0.220668,-0.220668,0.059941,-0.220668,0.575219,0.575219,0.575219,0.575219,0.529314
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,1746.6,1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,2.066135,0.764347,0.764347,0.388329,0.388329,0.987759,0.764347,0.359615,0.359615,0.359615,0.359615,0.358343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,6911.6,1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,1.369284,3.486651,3.486651,1.187611,1.187611,0.719713,3.486651,0.575219,0.575219,0.575219,0.575219,0.529314
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,6286.9,0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,-0.668055,-0.577960,-0.577960,-0.371110,-0.371110,0.751372,-0.577960,0.521154,0.521154,0.521154,0.521154,0.630418
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,18071.6,0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,-0.885628,NaN,-0.402992,NaN,-0.228196,0.369776,NaN,0.359851,0.359851,0.359851,0.359851,0.406323
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,15444.2,0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,0.344919,NaN,-0.402992,NaN,-0.228196,0.422963,NaN,0.359851,0.359851,0.359851,0.359851,0.406323
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,67148.0,0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,-0.538083,0.458129,0.458129,0.139802,0.139802,0.084846,0.139802,1.023333,1.023333,1.023333,1.023333,0.786744

---------------

In [27]:
# F2, F3, F4 Z-score의 단순합산

merged_df['Z_sum'] = merged_df['F2_Z'] + merged_df['F3_Z'] + merged_df['F4_Z']
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,...,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean,F2_sct_Z,Z_sum
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN,-0.798240,...,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,NaN
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1,0.685487,...,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN,2.634169
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1,0.388741,...,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN,0.664001
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8,-0.649867,...,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN,-0.365797
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2,0.685487,...,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN,0.764347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8,0.982232,...,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN,3.486651
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5,-0.798240,...,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN,-0.577960
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN,-0.946613,...,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,NaN
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN,-0.204749,...,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,NaN
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8,-0.056377,...,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN,0.458129

In [28]:
pd.set_option('display.max_columns',None)

In [29]:
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean,F2_sct_Z,Z_sum
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,NaN
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN,2.634169
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN,0.664001
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN,-0.365797
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN,0.764347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN,3.486651
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN,-0.577960
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,NaN
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,NaN
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN,0.458129

In [30]:
merged_df['Sector'].unique()

array(['Health Care', 'Financials', 'Industrials', 'Real Estate',
       'Information Technology', 'Consumer Staples',
       'Consumer Discretionary', 'Utilities', 'Materials',
       'Communication Services', 'Energy'], dtype=object)

In [31]:
# Z_sum의 합 중 NA는 섹터평균으로 치환

merged_df['Z_sum_NA_sct_mean'] = merged_df.groupby(['Sector'])['Z_sum'].transform(lambda x: x.fillna(x.mean()))
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean,F2_sct_Z,Z_sum,Z_sum_NA_sct_mean
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,"5,365.9",0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,NaN,-0.353361
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,"2,147.2",1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN,2.634169,2.634169
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,"14,320.7",0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN,0.664001,0.664001
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,"84,749.9",0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN,-0.365797,-0.365797
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,"1,746.6",1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN,0.764347,0.764347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,"6,911.6",1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN,3.486651,3.486651
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,"6,286.9",0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN,-0.577960,-0.577960
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,"18,071.6",0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,NaN,-0.402992
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,"15,444.2",0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,NaN,-0.402992
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,"67,148.0",0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN,0.458129,0.458129

In [32]:
merged_df.to_csv('ncheck.csv')

In [33]:
# F1 float으로 변환

merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2370 entries, 0 to 2369
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Symbol             2370 non-null   object
 1   Company_Name       2370 non-null   object
 2   Country            2370 non-null   object
 3   Sector             2370 non-null   object
 4   Industry           2370 non-null   object
 5   F1                 2369 non-null   object
 6   F2                 2366 non-null   float64
 7   F3                 2366 non-null   float64
 8   F4                 2083 non-null   float64
 9   F2_Z               2366 non-null   float64
 10  F3_Z               2366 non-null   float64
 11  F4_Z               2083 non-null   float64
 12  F2_ctr_mean        2369 non-null   float64
 13  F3_ctr_mean        2369 non-null   float64
 14  F4_ctr_mean        2367 non-null   float64
 15  F2_ctr_std         2366 non-null   float64
 16  F3_ctr_std         2366 non-null   float64
 17  F4_ctr_std         2366 non-null   float64
 18  F2_ctr_Z           2363 non-null   float64
 19  F3_ctr_Z           2363 non-null   float64
 20  F4_ctr_Z           2082 non-null   float64
 21  F2_sct_mean        0 non-null      float64
 22  F2_sct_Z           0 non-null      float64
 23  Z_sum              2083 non-null   float64
 24  Z_sum_NA_sct_mean  2370 non-null   float64
dtypes: float64(19), object(6)
memory usage: 481.4+ KB

In [34]:
merged_df['F1'] = merged_df['F1'].astype('str')
merged_df['F1'] = merged_df['F1'].apply(process_number)

In [35]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2370 entries, 0 to 2369
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Symbol             2370 non-null   object
 1   Company_Name       2370 non-null   object
 2   Country            2370 non-null   object
 3   Sector             2370 non-null   object
 4   Industry           2370 non-null   object
 5   F1                 2369 non-null   float64
 6   F2                 2366 non-null   float64
 7   F3                 2366 non-null   float64
 8   F4                 2083 non-null   float64
 9   F2_Z               2366 non-null   float64
 10  F3_Z               2366 non-null   float64
 11  F4_Z               2083 non-null   float64
 12  F2_ctr_mean        2369 non-null   float64
 13  F3_ctr_mean        2369 non-null   float64
 14  F4_ctr_mean        2367 non-null   float64
 15  F2_ctr_std         2366 non-null   float64
 16  F3_ctr_std         2366 non-null   float64
 17  F4_ctr_std         2366 non-null   float64
 18  F2_ctr_Z           2363 non-null   float64
 19  F3_ctr_Z           2363 non-null   float64
 20  F4_ctr_Z           2082 non-null   float64
 21  F2_sct_mean        0 non-null      float64
 22  F2_sct_Z           0 non-null      float64
 23  Z_sum              2083 non-null   float64
 24  Z_sum_NA_sct_mean  2370 non-null   float64
dtypes: float64(20), object(5)
memory usage: 481.4+ KB

In [36]:
# F2, F3, F4 Z-score의 가중평균

merged_df['Z_wt_sum'] = 0.5*merged_df['F2_Z'] + 0.3*merged_df['F3_Z'] + 0.2*merged_df['F4_Z']
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean,F2_sct_Z,Z_sum,Z_sum_NA_sct_mean,Z_wt_sum
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,5365.9,0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,NaN,-0.353361,NaN
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,2147.2,1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN,2.634169,2.634169,0.772876
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,14320.7,0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN,0.664001,0.664001,0.279236
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,84749.9,0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN,-0.365797,-0.365797,-0.220668
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,1746.6,1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN,0.764347,0.764347,0.388329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,6911.6,1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN,3.486651,3.486651,1.187611
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,6286.9,0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN,-0.577960,-0.577960,-0.371110
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,18071.6,0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,NaN,-0.402992,NaN
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,15444.2,0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,NaN,-0.402992,NaN
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,67148.0,0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN,0.458129,0.458129,0.139802

In [37]:
# Z_wt_sum의 합 중 NA는 섹터평균으로 치환

merged_df['Z_wt_sum_NA_sct_mean'] = merged_df.groupby(['Sector'])['Z_wt_sum'].transform(lambda x: x.fillna(x.mean()))
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean,F2_sct_Z,Z_sum,Z_sum_NA_sct_mean,Z_wt_sum,Z_wt_sum_NA_sct_mean
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,5365.9,0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,NaN,-0.353361,NaN,-0.230165
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,2147.2,1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN,2.634169,2.634169,0.772876,0.772876
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,14320.7,0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN,0.664001,0.664001,0.279236,0.279236
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,84749.9,0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN,-0.365797,-0.365797,-0.220668,-0.220668
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,1746.6,1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN,0.764347,0.764347,0.388329,0.388329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,6911.6,1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN,3.486651,3.486651,1.187611,1.187611
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,6286.9,0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN,-0.577960,-0.577960,-0.371110,-0.371110
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,18071.6,0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,15444.2,0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,67148.0,0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN,0.458129,0.458129,0.139802,0.139802

In [38]:
# F1(시총) 랭크

merged_df['F1_pct_rank'] = merged_df['F1'].rank(ascending = False, pct = True)
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean,F2_sct_Z,Z_sum,Z_sum_NA_sct_mean,Z_wt_sum,Z_wt_sum_NA_sct_mean,F1_pct_rank
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,5365.9,0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,NaN,-0.353361,NaN,-0.230165,0.802448
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,2147.2,1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN,2.634169,2.634169,0.772876,0.772876,0.978472
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,14320.7,0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN,0.664001,0.664001,0.279236,0.279236,0.447868
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,84749.9,0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN,-0.365797,-0.365797,-0.220668,-0.220668,0.059941
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,1746.6,1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN,0.764347,0.764347,0.388329,0.388329,0.987759
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,6911.6,1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN,3.486651,3.486651,1.187611,1.187611,0.719713
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,6286.9,0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN,-0.577960,-0.577960,-0.371110,-0.371110,0.751372
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,18071.6,0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.369776
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,15444.2,0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.422963
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,67148.0,0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN,0.458129,0.458129,0.139802,0.139802,0.084846

In [39]:
# F1(시총) 랭크 상위 50%는 Z-score 가중평균, 하위 50%는 단순평균

import numpy as np

merged_df['Z_comb'] = np.where(merged_df['F1_pct_rank'] <= 0.5, merged_df['Z_wt_sum'], merged_df['Z_sum'])
merged_df

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean,F2_sct_Z,Z_sum,Z_sum_NA_sct_mean,Z_wt_sum,Z_wt_sum_NA_sct_mean,F1_pct_rank,Z_comb
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,5365.9,0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,NaN,-0.353361,NaN,-0.230165,0.802448,NaN
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,2147.2,1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN,2.634169,2.634169,0.772876,0.772876,0.978472,2.634169
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,14320.7,0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN,0.664001,0.664001,0.279236,0.279236,0.447868,0.279236
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,84749.9,0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN,-0.365797,-0.365797,-0.220668,-0.220668,0.059941,-0.220668
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,1746.6,1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN,0.764347,0.764347,0.388329,0.388329,0.987759,0.764347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,6911.6,1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN,3.486651,3.486651,1.187611,1.187611,0.719713,3.486651
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,6286.9,0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN,-0.577960,-0.577960,-0.371110,-0.371110,0.751372,-0.577960
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,18071.6,0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.369776,NaN
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,15444.2,0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.422963,NaN
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,67148.0,0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN,0.458129,0.458129,0.139802,0.139802,0.084846,0.139802

In [40]:
# F2의 유니버스, 국가, 섹터별 Z-score 상관관계

merged_df[['F2','F2_Z','F2_ctr_Z','F2_sct_Z','Z_sum','Z_wt_sum']].corr()

                F2      F2_Z  F2_ctr_Z  F2_sct_Z     Z_sum  Z_wt_sum
F2        1.000000  1.000000  0.800303       NaN  0.686973  0.863336
F2_Z      1.000000  1.000000  0.800303       NaN  0.686973  0.863336
F2_ctr_Z  0.800303  0.800303  1.000000       NaN  0.531530  0.677589
F2_sct_Z       NaN       NaN       NaN       NaN       NaN       NaN
Z_sum     0.686973  0.686973  0.531530       NaN  1.000000  0.953438
Z_wt_sum  0.863336  0.863336  0.677589       NaN  0.953438  1.000000

In [41]:
# Industry 별 스탯

pd.pivot_table(merged_df, index=['Industry'], columns=['Country'], values=['Z_wt_sum'], aggfunc='mean')

                                     Z_wt_sum                          \
Country                             Australia Austria Belgium Bermuda
Industry
Aerospace & Defense                       NaN     NaN     NaN     NaN
Air Freight & Logistics                   NaN     NaN     NaN     NaN
Airlines                                  NaN     NaN     NaN     NaN
Auto Components                           NaN     NaN     NaN     NaN
Automobiles                               NaN     NaN     NaN     NaN
...                                       ...     ...     ...     ...
Tobacco                                   NaN     NaN     NaN     NaN
Trading Companies & Distributors    -0.435955     NaN     NaN     NaN
Transportation Infrastructure             NaN     NaN     NaN     NaN
Water Utilities                           NaN     NaN     NaN     NaN
Wireless Telecommunication Services       NaN     NaN     NaN     NaN

                                                                         \
Country                                Brazil    Canada Chile     China
Industry
Aerospace & Defense                       NaN -0.689486   NaN  0.187701
Air Freight & Logistics                   NaN       NaN   NaN       NaN
Airlines                                  NaN       NaN   NaN       NaN
Auto Components                           NaN -0.104840   NaN -0.087253
Automobiles                               NaN       NaN   NaN  0.304850
...                                       ...       ...   ...       ...
Tobacco                                   NaN       NaN   NaN -0.125749
Trading Companies & Distributors          NaN -0.489336   NaN       NaN
Transportation Infrastructure       -0.547896       NaN   NaN  0.674187
Water Utilities                     -0.230265       NaN   NaN       NaN
Wireless Telecommunication Services -0.339046 -0.296143   NaN       NaN

                                                                       \
Country                             Colombia Czech Republic   Denmark
Industry
Aerospace & Defense                      NaN            NaN       NaN
Air Freight & Logistics                  NaN            NaN -0.396879
Airlines                                 NaN            NaN       NaN
Auto Components                          NaN            NaN       NaN
Automobiles                              NaN            NaN       NaN
...                                      ...            ...       ...
Tobacco                                  NaN            NaN       NaN
Trading Companies & Distributors         NaN            NaN       NaN
Transportation Infrastructure            NaN            NaN       NaN
Water Utilities                          NaN            NaN       NaN
Wireless Telecommunication Services      NaN            NaN       NaN

                                                                           \
Country                                 Egypt Finland    France   Germany
Industry
Aerospace & Defense                       NaN     NaN -0.508577 -0.605099
Air Freight & Logistics                   NaN     NaN       NaN  0.200657
Airlines                                  NaN     NaN       NaN       NaN
Auto Components                           NaN     NaN  0.059004  0.276843
Automobiles                               NaN     NaN  2.169956  1.208614
...                                       ...     ...       ...       ...
Tobacco                              1.135696     NaN       NaN       NaN
Trading Companies & Distributors          NaN     NaN       NaN -0.294271
Transportation Infrastructure             NaN     NaN       NaN       NaN
Water Utilities                           NaN     NaN       NaN       NaN
Wireless Telecommunication Services       NaN     NaN       NaN       NaN

                                                                        \
Country                             Greece Hong Kong Hungary     India
Industry
Aerospace & Defense                    NaN       NaN     NaN -0.451689
Air Freight & Logistics                NaN       NaN     NaN       NaN
Airlines                               NaN       NaN     NaN       NaN
Auto Components                        NaN       NaN     NaN -0.507083
Automobiles                            NaN -0.319307     NaN -0.473446
...                                    ...       ...     ...       ...
Tobacco                                NaN       NaN     NaN -0.206578
Trading Companies & Distributors       NaN       NaN     NaN -0.770421
Transportation Infrastructure          NaN  1.792169     NaN -0.568461
Water Utilities                        NaN  0.634719     NaN       NaN
Wireless Telecommunication Services    NaN       NaN     NaN -0.340025

                                                                            \
Country                             Indonesia   Ireland   Israel     Italy
Industry
Aerospace & Defense                       NaN       NaN -0.44464       NaN
Air Freight & Logistics                   NaN       NaN      NaN       NaN
Airlines                                  NaN       NaN      NaN       NaN
Auto Components                           NaN -0.694843      NaN       NaN
Automobiles                         -0.034988       NaN      NaN -0.634587
...                                       ...       ...      ...       ...
Tobacco                              0.839403       NaN      NaN       NaN
Trading Companies & Distributors          NaN  0.231119      NaN       NaN
Transportation Infrastructure             NaN       NaN      NaN -0.138989
Water Utilities                           NaN       NaN      NaN       NaN
Wireless Telecommunication Services       NaN       NaN      NaN       NaN

                                                                              \
Country                                 Japan    Kuwait Luxembourg  Malaysia
Industry
Aerospace & Defense                       NaN       NaN        NaN       NaN
Air Freight & Logistics             -0.023956  0.023207        NaN       NaN
Airlines                                  NaN       NaN        NaN       NaN
Auto Components                      0.314651       NaN        NaN       NaN
Automobiles                          0.569166       NaN        NaN       NaN
...                                       ...       ...        ...       ...
Tobacco                              0.394786       NaN        NaN       NaN
Trading Companies & Distributors     0.329414       NaN        NaN       NaN
Transportation Infrastructure             NaN       NaN        NaN -0.624162
Water Utilities                           NaN       NaN        NaN       NaN
Wireless Telecommunication Services  0.074077  0.004968        NaN -0.296650

                                                                              \
Country                                Mexico Netherlands New Zealand Norway
Industry
Aerospace & Defense                       NaN   -0.517395         NaN    NaN
Air Freight & Logistics                   NaN         NaN         NaN    NaN
Airlines                                  NaN         NaN         NaN    NaN
Auto Components                           NaN         NaN         NaN    NaN
Automobiles                               NaN    0.142108         NaN    NaN
...                                       ...         ...         ...    ...
Tobacco                                   NaN         NaN         NaN    NaN
Trading Companies & Distributors          NaN   -0.462573         NaN    NaN
Transportation Infrastructure       -0.153602         NaN   -0.307334    NaN
Water Utilities                           NaN         NaN         NaN    NaN
Wireless Telecommunication Services -0.252647         NaN         NaN    NaN

                                                                            \
Country                             Peru Philippines Poland Portugal Qatar
Industry
Aerospace & Defense                  NaN         NaN    NaN      NaN   NaN
Air Freight & Logistics              NaN         NaN    NaN      NaN   NaN
Airlines                             NaN         NaN    NaN      NaN   NaN
Auto Components                      NaN         NaN    NaN      NaN   NaN
Automobiles                          NaN         NaN    NaN      NaN   NaN
...                                  ...         ...    ...      ...   ...
Tobacco                              NaN         NaN    NaN      NaN   NaN
Trading Companies & Distributors     NaN         NaN    NaN      NaN   NaN
Transportation Infrastructure        NaN   -0.305546    NaN      NaN   NaN
Water Utilities                      NaN         NaN    NaN      NaN   NaN
Wireless Telecommunication Services  NaN   -0.089622    NaN      NaN   NaN

                                                                         \
Country                             Saudi Arabia Singapore South Africa
Industry
Aerospace & Defense                          NaN -0.285835          NaN
Air Freight & Logistics                      NaN       NaN          NaN
Airlines                                     NaN       NaN          NaN
Auto Components                              NaN       NaN          NaN
Automobiles                                  NaN       NaN          NaN
...                                          ...       ...          ...
Tobacco                                      NaN       NaN          NaN
Trading Companies & Distributors             NaN  0.272112          NaN
Transportation Infrastructure                NaN       NaN          NaN
Water Utilities                              NaN       NaN          NaN
Wireless Telecommunication Services     0.075281       NaN    -0.176771

                                                                     \
Country                             South Korea     Spain    Sweden
Industry
Aerospace & Defense                   -0.713774       NaN       NaN
Air Freight & Logistics                0.055052       NaN       NaN
Airlines                                    NaN       NaN       NaN
Auto Components                        0.501667       NaN       NaN
Automobiles                            0.758151       NaN       NaN
...                                         ...       ...       ...
Tobacco                                0.401475       NaN -0.527268
Trading Companies & Distributors            NaN       NaN       NaN
Transportation Infrastructure               NaN -0.811241       NaN
Water Utilities                             NaN       NaN       NaN
Wireless Telecommunication Services    0.520972       NaN  0.287003

                                                                               \
Country                             Switzerland    Taiwan  Thailand    Turkey
Industry
Aerospace & Defense                         NaN       NaN       NaN -0.224964
Air Freight & Logistics                     NaN       NaN       NaN       NaN
Airlines                                    NaN       NaN       NaN       NaN
Auto Components                             NaN  0.320367       NaN       NaN
Automobiles                                 NaN       NaN       NaN  0.098787
...                                         ...       ...       ...       ...
Tobacco                                     NaN       NaN       NaN       NaN
Trading Companies & Distributors            NaN       NaN       NaN       NaN
Transportation Infrastructure               NaN -0.250283 -0.666986       NaN
Water Utilities                             NaN       NaN       NaN       NaN
Wireless Telecommunication Services         NaN -0.213011 -0.319420 -0.003445

                                                                         \
Country                             United Arab Emirates United Kingdom
Industry
Aerospace & Defense                                  NaN      -0.180561
Air Freight & Logistics                              NaN            NaN
Airlines                                             NaN            NaN
Auto Components                                      NaN            NaN
Automobiles                                          NaN            NaN
...                                                  ...            ...
Tobacco                                              NaN       0.423701
Trading Companies & Distributors                     NaN      -0.431837
Transportation Infrastructure                        NaN            NaN
Water Utilities                                      NaN      -0.301200
Wireless Telecommunication Services                  NaN       0.825570


Country                             United States
Industry
Aerospace & Defense                     -0.509417
Air Freight & Logistics                 -0.235085
Airlines                                -0.790496
Auto Components                         -0.222897
Automobiles                              0.172127
...                                           ...
Tobacco                                 -0.268863
Trading Companies & Distributors        -0.521524
Transportation Infrastructure                 NaN
Water Utilities                         -0.227038
Wireless Telecommunication Services     -0.582097

[69 rows x 49 columns]

In [42]:
# 다른 데이터셋 추가

df2 = pd.read_csv('Supplementary data.csv')
df2

      Symbol  05/20/2022  05/13/2022  05/06/2022  04/29/2022
0     BKS3RS    5.311775   -6.954479    7.181740  -11.391473
1     BFMV9Y    5.079603    0.533533   -9.078312    3.218889
2     B1YW44   -4.874891    2.816439   -6.402314   -4.332524
3     259570   -2.665776   -0.153810    3.681874   -3.318357
4     BY9D3L    3.837347    5.361307   -5.989683   -0.190026
...      ...         ...         ...         ...         ...
2365  B544N7    5.727279   -3.949815   -1.981086   -3.935415
2366  B292RC   -0.905871    0.345135   -2.371532  -13.399017
2367  BZ00V3  -10.663706  -11.397022  -14.698630   -1.806557
2368  B04KP8    3.092027    2.490830   -8.675581    5.355513
2369  598381   -3.171784    0.776648   -1.142430   -1.583564

[2370 rows x 5 columns]

In [43]:
df2 = df2.fillna(0)

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2370 entries, 0 to 2369
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Symbol      2370 non-null   object
 1   05/20/2022  2370 non-null   float64
 2   05/13/2022  2370 non-null   float64
 3   05/06/2022  2370 non-null   float64
 4   04/29/2022  2370 non-null   float64
dtypes: float64(4), object(1)
memory usage: 92.7+ KB

In [45]:
# Numpy 패키지 일부(?)

from scipy import stats

In [46]:
# Q. 여러개의 칼럼에 /100 하는 방법?

def process_multiply(data):
    return float(data.multiply(100))

df2[['05/20/2022_d', '05/13/2022_d', '05/06/2022_d', '04/29/2022_d']] = df2[['05/20/2022', '05/13/2022', '05/06/2022', '04/29/2022']] / 100

In [47]:
help(stats.gmean)

Help on function gmean in module scipy.stats.stats:

gmean(a, axis=0, dtype=None, weights=None)
    Compute the geometric mean along the specified axis.

    Return the geometric average of the array elements.
    That is:  n-th root of (x1 * x2 * ... * xn)

    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : int or None, optional
        Axis along which the geometric mean is computed. Default is 0.
        If None, compute over the whole array `a`.
    dtype : dtype, optional
        Type of the returned array and of the accumulator in which the
        elements are summed. If dtype is not specified, it defaults to the
        dtype of a, unless a has an integer dtype with a precision less than
        that of the default platform integer. In that case, the default
        platform integer is used.
    weights : array_like, optional
        The weights array can either be 1-D (in which case its length must be
        the size of `a` along the given `axis`) or of the same shape as `a`.
        Default is None, which gives each value a weight of 1.0.

    Returns
    -------
    gmean : ndarray
        See `dtype` parameter above.

    See Also
    --------
    numpy.mean : Arithmetic average
    numpy.average : Weighted average
    hmean : Harmonic mean

    Notes
    -----
    The geometric average is computed over a single dimension of the input
    array, axis=0 by default, or all values in the array if axis=None.
    float64 intermediate and return values are used for integer inputs.

    Use masked arrays to ignore any non-finite values in the input or that
    arise in the calculations such as Not a Number and infinity because masked
    arrays automatically mask any non-finite values.

    References
    ----------
    .. [1] "Weighted Geometric Mean", *Wikipedia*, https://en.wikipedia.org/wiki/Weighted_geometric_mean.

    Examples
    --------
    >>> from scipy.stats import gmean
    >>> gmean([1, 4])
    2.0
    >>> gmean([1, 2, 3, 4, 5, 6, 7])
    3.3800151591412964

In [48]:
func(a, axis=...., *kwargs)

SyntaxError: invalid syntax (1/ipykernel_22656/3430156764.py, line 1)

In [ ]:
# Geometric mean 계산

# df2['geo_mean'] = stats.gmean(df2[['05/20/2022_d', '05/13/2022_d', '05/06/2022_d', '04/29/2022_d']], axis=1)
def process_mean(row):
    return row.mean()
df2['geo_mean2'] = df2[['05/20/2022_d', '05/13/2022_d', '05/06/2022_d', '04/29/2022_d']].apply(process_mean)

In [ ]:
df2[['05/20/2022_d', '05/13/2022_d', '05/06/2022_d', '04/29/2022_d']]

      05/20/2022_d  05/13/2022_d  05/06/2022_d  04/29/2022_d
0         0.053118     -0.069545      0.071817     -0.113915
1         0.050796      0.005335     -0.090783      0.032189
2        -0.048749      0.028164     -0.064023     -0.043325
3        -0.026658     -0.001538      0.036819     -0.033184
4         0.038373      0.053613     -0.059897     -0.001900
...            ...           ...           ...           ...
2365      0.057273     -0.039498     -0.019811     -0.039354
2366     -0.009059      0.003451     -0.023715     -0.133990
2367     -0.106637     -0.113970     -0.146986     -0.018066
2368      0.030920      0.024908     -0.086756      0.053555
2369     -0.031718      0.007766     -0.011424     -0.015836

[2370 rows x 4 columns]

Empty DataFrame
Columns: [Symbol, 05/20/2022, 05/13/2022, 05/06/2022, 04/29/2022, geo_mean, glink, 05/20/2022_d, 05/13/2022_d, 05/06/2022_d, 04/29/2022_d]
Index: []

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2370 entries, 0 to 2369
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Symbol      2370 non-null   object
 1   05/20/2022  2341 non-null   float64
 2   05/13/2022  2341 non-null   float64
 3   05/06/2022  2341 non-null   float64
 4   04/29/2022  2251 non-null   float64
 5   geo_mean    11 non-null     float64
dtypes: float64(5), object(1)
memory usage: 111.2+ KB

In [ ]:
kwargs => extra args

In [ ]:
df2

      Symbol  05/20/2022  05/13/2022  05/06/2022  04/29/2022  geo_mean
0     BKS3RS    5.311775   -6.954479    7.181740  -11.391473       NaN
1     BFMV9Y    5.079603    0.533533   -9.078312    3.218889       NaN
2     B1YW44   -4.874891    2.816439   -6.402314   -4.332524       NaN
3     259570   -2.665776   -0.153810    3.681874   -3.318357       NaN
4     BY9D3L    3.837347    5.361307   -5.989683   -0.190026       NaN
...      ...         ...         ...         ...         ...       ...
2365  B544N7    5.727279   -3.949815   -1.981086   -3.935415       NaN
2366  B292RC   -0.905871    0.345135   -2.371532  -13.399017       NaN
2367  BZ00V3  -10.663706  -11.397022  -14.698630   -1.806557       NaN
2368  B04KP8    3.092027    2.490830   -8.675581    5.355513       NaN
2369  598381   -3.171784    0.776648   -1.142430   -1.583564       NaN

[2370 rows x 6 columns]

In [ ]:
# Geo linking 단순계산

df2['glink'] = ((1 + df2['05/20/2022']/100) * (1 + df2['05/13/2022']/100) * (1 + df2['05/06/2022']/100) * (1 + df2['04/29/2022']/100)) -1

In [ ]:
df2

,Symbol,05/20/2022,05/13/2022,05/06/2022,04/29/2022,geo_mean,glink
0,BKS3RS,5.311775,-6.954479,7.181740,-11.391473,NaN,-0.069388
1,BFMV9Y,5.079603,0.533533,-9.078312,3.218889,NaN,-0.008584
2,B1YW44,-4.874891,2.816439,-6.402314,-4.332524,NaN,-0.124236
3,259570,-2.665776,-0.153810,3.681874,-3.318357,NaN,-0.025809
4,BY9D3L,3.837347,5.361307,-5.989683,-0.190026,NaN,0.026560
...,...,...,...,...,...,...,...
2365,B544N7,5.727279,-3.949815,-1.981086,-3.935415,NaN,-0.043779
2366,B292RC,-0.905871,0.345135,-2.371532,-13.399017,NaN,-0.159295
2367,BZ00V3,-10.663706,-11.397022,-14.698630,-1.806557,NaN,-0.336998
2368,B04KP8,3.092027,2.490830,-8.675581,5.355513,NaN,0.016610
2369,598381,-3.171784,0.776648,-1.142430,-1.583564,NaN,-0.050621

In [ ]:
merged_df2 = pd.merge(merged_df, df2, on=['Symbol'], how='left')
merged_df2

,Symbol,Company_Name,Country,Sector,Industry,F1,F2,F3,F4,F2_Z,F3_Z,F4_Z,F2_ctr_mean,F3_ctr_mean,F4_ctr_mean,F2_ctr_std,F3_ctr_std,F4_ctr_std,F2_ctr_Z,F3_ctr_Z,F4_ctr_Z,F2_sct_mean,F2_sct_Z,Z_sum,Z_sum_NA_sct_mean,Z_wt_sum,Z_wt_sum_NA_sct_mean,F1_pct_rank,Z_comb,05/20/2022,05/13/2022,05/06/2022,04/29/2022,geo_mean,glink
0,BKS3RS,10x Genomics Inc Class A,United States,Health Care,Life Sciences Tools & Services,5365.9,0.1,0.0,NaN,-0.798240,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.728275,-0.979775,NaN,NaN,NaN,NaN,-0.353361,NaN,-0.230165,0.802448,NaN,5.311775,-6.954479,7.181740,-11.391473,NaN,-0.069388
1,BFMV9Y,"360 DigiTech, Inc. ADR Class A",China,Financials,Consumer Finance,2147.2,1.1,3.8,103.1,0.685487,0.403961,1.544722,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,0.048100,1.209869,NaN,NaN,2.634169,2.634169,0.772876,0.772876,0.978472,2.634169,5.079603,0.533533,-9.078312,3.218889,NaN,-0.008584
2,B1YW44,3i Group plc,United Kingdom,Financials,Capital Markets,14320.7,0.9,3.5,16.1,0.388741,0.298133,-0.022873,0.658621,3.514943,2.017568,0.574366,2.629552,29.821590,0.420254,-0.005683,0.472223,NaN,NaN,0.664001,0.664001,0.279236,0.279236,0.447868,0.279236,-4.874891,2.816439,-6.402314,-4.332524,NaN,-0.124236
3,259570,3M Company,United States,Industrials,Industrial Conglomerates,84749.9,0.2,4.0,6.8,-0.649867,0.474513,-0.190443,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-0.393938,1.411554,-0.268326,NaN,NaN,-0.365797,-0.365797,-0.220668,-0.220668,0.059941,-0.220668,-2.665776,-0.153810,3.681874,-3.318357,NaN,-0.025809
4,BY9D3L,"3SBio, Inc.",China,Health Care,Biotechnology,1746.6,1.1,3.5,5.2,0.685487,0.298133,-0.219273,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.062139,-0.013483,-0.443898,NaN,NaN,0.764347,0.764347,0.388329,0.388329,0.987759,0.764347,3.837347,5.361307,-5.989683,-0.190026,NaN,0.026560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365,B544N7,Zoomlion Heavy Industry Science & Technology C...,China,Industrials,Machinery,6911.6,1.3,8.2,47.8,0.982232,1.956111,0.548308,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,0.237163,0.951319,0.275719,NaN,NaN,3.486651,3.486651,1.187611,1.187611,0.719713,3.486651,5.727279,-3.949815,-1.981086,-3.935415,NaN,-0.043779
2366,B292RC,"ZOZO, Inc.",Japan,Consumer Discretionary,Internet & Direct Marketing Retail,6286.9,0.1,2.2,38.5,-0.798240,-0.160457,0.380738,0.874231,2.538462,11.304819,0.667321,1.621424,35.234538,-1.160207,-0.208743,0.771833,NaN,NaN,-0.577960,-0.577960,-0.371110,-0.371110,0.751372,-0.577960,-0.905871,0.345135,-2.371532,-13.399017,NaN,-0.159295
2367,BZ00V3,"Zscaler, Inc.",United States,Information Technology,Software,18071.6,0.0,0.0,NaN,-0.946613,-0.936532,NaN,0.317827,1.638879,19.546914,0.299100,1.672710,47.505261,-1.062612,-0.979775,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.369776,NaN,-10.663706,-11.397022,-14.698630,-1.806557,NaN,-0.336998
2368,B04KP8,ZTE Corporation Class H,China,Information Technology,Communications Equipment,15444.2,0.5,2.3,NaN,-0.204749,-0.125181,NaN,1.028994,3.565680,31.477941,1.142699,4.871468,59.198172,-0.462934,-0.259815,NaN,NaN,NaN,NaN,-0.402992,NaN,-0.228196,0.422963,NaN,3.092027,2.490830,-8.675581,5.355513,NaN,0.016610
2369,598381,Zurich Insurance Group Ltd,Switzerland,Financials,Insurance,67148.0,0.6,4.5,9.8,-0.056377,0.650894,-0.136388,0.447619,2.616667,18.517500,0.473821,1.651594,20.426578,0.321600,1.140312,-0.426772,NaN,NaN,0.458129,0.458129,0.139802,0.139802,0.084846,0.139802,-3.171784,0.776648,-1.142430,-1.583564,NaN,-0.050621